on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      # TODO sandbox relax only for dprint plugins possible?
      # TODO file an issue in treefmt-nix repo about dprint plugins
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop --command bash -c "echo \$PATH | sed 's/:/\n/g'"
      - run: nix fmt

